[package]
name = "client"
version = "0.1.0"
authors = ["Rheydskey <matgag02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[lib]
crate-type = ["cdylib"]


[dependencies]
seed = "0.7.0"
wasm-bindgen = "0.2.68"

serde = { version = "1.0.116", features = ['derive'] }
serde_json = {version = "1.0.57"}
futures = "0.3.5"
shared =  {path = "../shared"}
reqwest = "0.10.8"

[profile.release]
lto = true
opt-level = 'z'
