[package]
name = "client"
version = "0.1.0"
authors = ["Rheydskey <matgag02@gmail.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]


[dependencies]
seed = {git = "https://github.com/seed-rs/seed.git", commit = "c631e75"}
wasm-bindgen = "0.2.69"
serde = { version = "1.0.118", features = ['derive'] }
serde_json = {version = "1.0.60"}
futures = "0.3.8"
shared =  {path = "../shared"}
reqwest = "0.10.10"

[profile.release]
lto = true
opt-level = 'z'
