[package]
name = "server"
version = "0.1.0"
authors = ["Rheydskey <matgag02@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
actix-rt = "1.1.1"
actix-files = "0.4.1"
actix-multipart = "0.3.0"
actix-service = "1.0.6"
actix-http = "2.2.0"
actix-utils = "2.0.0"

rand = "0.8.0"
zip = "0.5.8"
zip-extensions = "0.6.0"
tar = "0.4"

mime_guess = "2.0.3"

serde = {version = "1.0.118", features = ['derive']}
serde_json = "1.0.59"
serde_yaml = "0.8.14"

futures = "0.3.8"
tokio = {version = "0.3.6", features = ["full"]}
futures-core = "0.3.8"

env_logger = "0.8"
bytes = "0.6.0"

shared = {path = "../shared"}

sqlx = {version = "0.4.1", features = ["sqlite", "runtime-async-std-rustls"]}

time = "0.2.23"

async-std = "1.8.0"

chrono = "0.4.19"