[package]
name = "server"
version = "0.1.0"
authors = ["Rheydskey <matgag02@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-files = "0.2.2"
actix-multipart = "0.2.0"
actix-service = "1.0.5"
actix-http = "1.0.1"
actix-utils = "1.0.6"

zip = "0.5.6"
zip-extensions = "0.5.0"
tar = "0.4"
mime_guess = "2.0.3"

serde = {version = "1.0.114", features = ['derive']}
serde_json = "1.0.57"
serde_yaml = "0.8.13"

futures = "0.3.5"
tokio = "0.2.22"
futures-core = "0.3.5"

env_logger = "0.7"
bytes = "0.5.6"

shared = {path = "../shared"}
