[package]
name = "server"
version = "0.1.0"
authors = ["Rheydskey <matgag02@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.0.2"
actix-rt = "1.1.1"
actix-files = "0.4.0"
actix-multipart = "0.3.0"
actix-service = "1.0.6"
actix-http = "2.0.0"
actix-utils = "2.0.0"

rand = "0.7.3"
zip = "0.5.8"
zip-extensions = "0.5.0"
tar = "0.4"

mime_guess = "2.0.3"

serde = {version = "1.0.116", features = ['derive']}
serde_json = "1.0.57"
serde_yaml = "0.8.13"

futures = "0.3.5"
tokio = {version = "0.3.0", features = ["full"]}
futures-core = "0.3.5"

env_logger = "0.8"
bytes = "0.6.0"

shared = {path = "../shared"}

rusqlite = "0.24.0"

time = "0.2.22"

chrono = "0.4.19"