[package]
name = "server"
version = "0.1.0"
authors = ["Rheydskey <matgag02@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
serde ="1.0.105"
serde_json = "1.0.48"
actix-files = "0.2.1"
actix-multipart = "0.2.0"
actix-service = "1.0.5"
futures = "0.3.4"
shared = {path = "../shared"}
